kind: pipeline
type: docker
name: checks

steps:
  - name: lint
    image: node:10
    commands:
      - yarn --network-timeout 100000
      - yarn lint

---
kind: pipeline
type: docker
name: build & deploy

steps:
  - name: build preview
    image: docker/compose:1.24.1
    environment:
      REACT_APP_API_KEY:
        from_secret: REACT_APP_API_KEY
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose build preview
    depends_on:
      - clone
  - name: deploy preview
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p bee-api up -d preview
    depends_on:
      - build preview
