kind: pipeline
type: docker
name: checks

steps:
  - name: lint
    image: node:10
    commands:
      - yarn install --network-timeout 100000
      - yarn lint



---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: node:10
    commands:
      - yarn install --network-timeout 100000
      - yarn lint