version: '3'
services:
  preview:
    build:
      context: .
      args:
        - NODE_ENV=staging
        - REACT_APP_API_SECRET=${REACT_APP_API_SECRET}
        - REACT_APP_FIREBASE_SECRET=${REACT_APP_FIREBASE_SECRET}
    image: bee-api:staging
    restart: always
    labels:
      - "traefik.frontend.rule=Host:bee-api.cchampou.me"
      - "traefik.backend.port=5000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"

networks:
  default:
    external:
      name: layko_layko_net
